
curl -X POST http://localhost:8080/auth/login \
     -H "Content-Type: application/json" \
     -d '{"email": "joao@example.com", "senha": "123456"}'
     
###

curl -X GET http://localhost:8080/auth/perfil \
     -H "Authorization: Bearer eyJhbGciJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tZSI6Ikpvw6NvIFNpbHZhIiwiZW1haWwiOiJqb2FvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzMzNzgxMDM4LCJleHAiOjE3MzM3ODQ2Mzh9.Jzbvns_y7jtShkQFaZ90gcmHytj6orEkYkrBfWnhlAk" \
     -H "Content-Type: application/json"